CREATE DATABASE IF NOT EXISTS projeto_vendas;
USE projeto_vendas; 

CREATE TABLE IF NOT EXISTS produtos (
id INT AUTO_INCREMENT PRIMARY KEY, 
descricao VARCHAR(100) NOT NULL, 
preco DECIMAL(10,2) NOT NULL);

CREATE TABLE IF NOT EXISTS vendedores(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL);

CREATE TABLE IF NOT EXISTS vendas(
id INT AUTO_INCREMENT PRIMARY KEY,
id_vendedor INT NOT NULL,
desconto DECIMAL(10,2) DEFAULT 0,
valor_final DECIMAL(10,2) NOT NULL,
data_venda DATETIME DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT fk_vendedor
FOREIGN KEY (id_vendedor)
REFERENCES vendedores(id)
);

CREATE TABLE IF NOT EXISTS vendas_produtos(
id INT AUTO_INCREMENT PRIMARY KEY, 
id_venda INT NOT NULL,
id_produto INT NOT NULL,
quantidade INT NOT NULL, 
valor_unitario DECIMAL(10,2) NOT NULL,
valor_total DECIMAL(10,2) NOT NULL,

CONSTRAINT fk_venda
FOREIGN KEY (id_venda)
REFERENCES vendas(id)
ON DELETE CASCADE,

CONSTRAINT fk_produto
FOREIGN KEY (id_produto)
REFERENCES produtos(id)
);